### ISSUE TITLE
【Env】Docker 開発環境の構築

### ISSUE THREAD

**Issue by teri-shiba** [teri-shiba/minnaka-map#9]
## TODO: 
- [x] Docker / Rails 導入
- [x] health_check
- [x] Gem 追加
    - [x] pry
    - [x] rspec
    - [x] rubocop
- [x] Next.js 導入
    - [x] ESLint
- [x] Github Actions 自動 CI 設定
